defaults:
  - trainer: defaults
  - optimizer: adam
  - experiment: ???
  - server: ???
  - resume_overrides: no_overrides
data:
  n_steps_input: 6
  n_steps_output: 1
  normalization_type:
    _partial_: true
    _target_: the_well.data.normalization.ZScoreNormalization
  train_dataset: # options: WellDataset or DeltaWellDataset
    _partial_: true
    _target_: the_well.data.datasets.WellDataset
# model:
#   gradient_checkpointing: False
data_workers: 14
wandb_project_name: "the_well_extended_again"
