name: Tests

on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  pytest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: "3.10"
            cache: "pip"
        - name: Install the_well
          run: pip install .[benchmark,dev] --extra-index-url https://download.pytorch.org/whl/cpu
        - name: Run tests
          env:
            PYTHONPATH: ${{ github.workspace }}
            PY_COLORS: "1"
          run: pytest tests
