_target_: the_well.benchmark.trainer.Trainer_C
epochs: 500
val_frequency: 1
rollout_val_frequency: 2
short_validation_length: 20
max_rollout_steps: 20
num_time_intervals: 5
make_rollout_videos: True
checkpoint_frequency: 20 # Frequency of saving checkpoints. If 0, only use best/most recent. Setting this to 1 uses A LOT of disk space.
# enable_amp: False
loss_fn: ???
checkpoint_path: "" # This is a default that is overridden by the code
